parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sitpac
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_host: 127.0.0.1
    mailer_user: jorgeibarra87@gmail.com
    mailer_password: 87069640jorge
    locale: es
    secret: 26ff61e2d5d2473d39fd193913bf4239
    database_path: null
