backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

extranet:
    resource: "@ExtranetBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

pagina_ayuda:
    pattern: /ayuda
    defaults: { _controller: FrontendBundle:Default:ayuda }



# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
