parameters:
#    extranet.example.class: Sitpac\ExtranetBundle\Example

services:
#    extranet.example:
#        class: %extranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: Sitpac\ExtranetBundle\Listener\LoginListener
        arguments: [@security.context, @router, @session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }